### ISSUE TITLE
Support Distributions 0.24

### ISSUE THREAD

**Issue by mohamed82008** [devmotion/MCMCDiagnosticTools.jl#24]
Hi!

Is there any reason why this package requires Distributions 0.25? Would it be easy to support 0.24 as well?

**Comment by sethaxen** [comment]
Unfortunately I don't think so. R* returns a `PoissonBinomial` distribution (see https://github.com/devmotion/MCMCDiagnosticTools.jl/pull/7), which was broken until Distributions v0.25.4 (see https://github.com/JuliaStats/Distributions.jl/pull/1345)

**Comment by devmotion** [comment]
As @sethaxen said, the R* diagnostic requires Distributions 0.25. I had to make quite many changes in Distributions before R* could be added, e.g., it requires https://github.com/JuliaStats/Distributions.jl/pull/1286 (the PR that @sethaxen mentioned is only required to actually work with the resulting distribution but not for creating it in this package :smile:). So unfortunately, no, I don't think this package will support older versions of Distributions.

**Comment by mohamed82008** [comment]
I see, thanks.
